# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0138_userprofile_realm_name_in_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_sound',
            field=models.CharField(default='zulip', max_length=20),
        ),
    ]
